#!/bin/bash

# mm/mdl test for translation of the metamath base to the directory tree
# 1) first argument - the name of the source file to be 
#    translated 
# 2) second argument - the build directory from the top of
#    the project. By default, it's empty.

if [ -z $1 ] 
then echo "NO INPUT FILE."; exit
fi;

file=$1

if [ -z $2 ] 
then dir='';
else dir=$2'/';
fi;

mm_dir='mm/'
rus_dir='rus/'
smm_dir='smm/'

if ! [ -d $mm_dir ]
then
    mkdir $mm_dir;
fi;    
   
cd $mm_dir;

ulimit -c unlimited;

echo "================================================";
echo "cutting: ${file}.mm --> ${mm_dir}${file}.mm";
echo "================================================";
echo;

../../${dir}src/mm/mm \
	-w -v \
	--mem-all --info-all \
	--cut-source \
	-o ${file}.mm \
	\
	../${file}.mm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "================================================";
echo "translation: ${mm_dir}${file}.mm --> ${rus_dir}${file}.rus";
echo "================================================";
echo;

../../${dir}src/mm/mm \
	-v -w -t \
	--deep-translation \
	--mem-all --info-all \
	--correct-grammar ../grammar.corr \
	--correct-symbol ../symbol.corr \
	-o ../${rus_dir}${file}.rus \
	\
	${file}.mm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

cd ..;

if ! [ -d $rus_dir ]
then
    mkdir $rus_dir;
fi;  

cd $rus_dir;

echo "========================================";
echo "translation: ${rus_dir}${file}.rus --> ${smm_dir}${file}.smm";
echo "========================================";
echo;

../../${dir}src/mdl/mdl \
	-t -w -v \
	--deep-write \
	--mem-all --info-all \
	-o ../${smm_dir}${file}.smm \
	\
	${file}.rus;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

cd ..;

if ! [ -d $smm_dir ]
then
    mkdir $smm_dir;
fi;  

cd $smm_dir;

echo "========================================";
echo "verifying: ${smm_dir}${file}.smm with smm" ;
echo "========================================";
echo;

../../${dir}src/smm/smm \
	-v --show-stack \
	--mem-all --info-all \
	\
	${file}.smm;

if [ $? != 0 ] 
then 
    echo "TEST FAILED."; 
    exit
else 
    echo;
    echo;
    echo "Tests successfully passed :)"; 
fi;

