#!/bin/bash

if [ -z $1 ] 
then 
    echo;
    echo "mdl learninig / provig / compression test";
    echo "-----------------------------------------";
    echo "1 argument - the name <dir> of the directory to be used";
    echo "2 argument - the build directory from the top of the project. By default it's empty";
    echo;
    echo "the directory <dir> must contain:";
    echo "	file src.mm - the initial metamath source file";
    echo "	file thm - the list of theorem names, used for proving tests";
    echo "	file time - the list of time limits for proper test phases";
    echo;
    exit;
fi;

dir=$1;

if [ -z $2 ]
then
    build_dir='';
else
    build_dir=$2;
fi;

if [ ! -d ./$dir/tmp ]
then
    mkdir ./$dir/tmp;
fi;


./translate $dir $build_dir;

#./benchmark $dir $build_dir;
    
#./tune      $dir $build_dir;

count=0;
sum_factor=0;
sum_time=0;

show_phase="yes";
#clear="yes";
clear="no";

log=$dir/log;

if [ -f ./$log ]
then
    rm ./$log;
fi;
touch $log;

theorem_file=$dir/thm;    
   
while read theorem 
do
    if [ ${theorem:0:1} = "#" ]
    then
	continue;
    fi;

    if [ $show_phase = "yes" ]
    then
	echo "======================================";
	echo "compressing: $theorem in $dir ";
	echo "======================================";
	echo;
    fi;
    
    ./compress \
	  $dir \
	  $theorem \
	  $build_dir;
	  
    if [ $? != 0 ] 
    then 
	echo "COMPRESSIONG OF $theorem FAILED."; 
	exit 1;
    fi;
    
    factor_str=`cat ./compress.log | grep factor`;
    factor_array=($factor_str) 
    factor=${factor_array[1]}
    
    time_str=`cat ./prover.log | grep time`;
    time_array=($time_str) 
    time=${time_array[1]}
    
    echo "theorem $theorem" >> $log;
    echo "factor  $factor"  >> $log;
    echo "time    $time"    >> $log;
    echo                    >> $log;
    
    count=$(($count+1));
    sum_factor=`echo "scale=3; $sum_factor + $factor" | bc`;
    sum_time=`echo   "scale=3; $sum_time   + $time"   | bc`;
    
    if [ $show_phase = "yes" ]
    then
	echo;
	echo "compressing $theorem, factor: $factor, time: $time seconds"; 
	echo;
    fi;
    
done < $theorem_file;

rm ./compress.log;
rm ./prover.log;

if [ $clear = "yes" ]
then
    rm ./$log;
    #rm ./src.rus;
    #rm -fr ./$dir/tmp;
fi;

average_factor=`echo "scale=3; $sum_factor / $count" | bc`;
average_time=`echo   "scale=3; $sum_time   / $count" | bc`;

result_file=$dir/result;

if [ -f ./$result_file ]
then
    rm ./$result_file; 
fi;
touch $result_file;
    
echo "average_factor $average_factor" >> ./$result_file;
echo "average_time   $average_time"   >> ./$result_file;

echo "Average compression factor: $average_factor";
echo "Average proving time:       $average_time";

echo;
echo "Compression successfully completed :)"; 


