#!/bin/bash

if [ -z $1 ] 
then 
    echo;
    echo "mdl tuning - a meta-learning step";
    echo "---------------------------------";
    echo "1 argument - the name <dir> of the directory to be used";
    echo "2 argument - the build directory from the top of the project. By default it's empty";
    echo;
    exit;
fi;

dir=$1;

if [ -z $2 ] 
then 
    build_dir='';
else 
    build_dir=$2'/';
fi;

source=$dir/src.rus;
target=$dir/tmp/tuned.conf;
config=$dir/tmp/bench.conf;

if [ -f ./$target ]
then
    exit;
fi;

time_str=`cat ./$dir/time | grep tune`;
time_array=($time_str) 
time=${time_array[1]}

#echo "time = $time";

show_phase="yes";

if [ $show_phase = "yes" ]
then
    echo "======================================";
    echo "tuniing with: $source";
    echo "======================================";
    echo;
fi;
    
../../${build_dir}src/mdl/mdl \
	--verbose-med \
	--overwrite \
	--config $config \
	--tune \
	--time-limit $time \
	-o $target \
	\
	$source;
    
if [ $? != 0 ] 
then 
    echo "TUNING WITH FILE $source FAILED."; 
    exit 1;
fi;
    
echo;
echo "Tuning successfully completed :)"; 


