#!/bin/bash

# mm/mdl test for translation of the metamath base to the directory tree
# argument - the name of the source file to be translated 
# without extension (!!!)

if [ -z $1 ] 
then echo "NO INPUT FILE."; exit
fi;

file=$1

# We are located at /usr/share/mdl/scripts

math_dir='../math'; 
bin_dir='../../../../bin';

mm_dir='mm'
rus_dir='rus'
smm_dir='smm'

if ! [ -d ${math_dir} ]
then
    mkdir ${math_dir};
fi;    
   
cd ${math_dir};

if ! [ -d $mm_dir ]
then
    mkdir $mm_dir;
fi;    

#ulimit -c unlimited;

cd ${mm_dir}

echo "================================================";
echo "cutting: ${file}.mm --> ${mm_dir}/${file}.mm";
echo "================================================";
echo;

${bin_dir}/mm \
	-w -v \
	--mem-all --info-all \
	--cut-source \
	-o ${file}.mm \
	\
	../${file}.mm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "================================================";
echo "translation: ${mm_dir}/${file}.mm --> ${rus_dir}/${file}.rus";
echo "================================================";
echo;

${bin_dir}/mm \
	-v -w -t \
	--deep-translation \
	--mem-all --info-all \
	--correct-grammar ../grammar.corr \
	--correct-symbol ../symbol.corr \
	-o ../${rus_dir}/${file}.rus \
	\
	${file}.mm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

cd ..;

if ! [ -d $rus_dir ]
then
    mkdir $rus_dir;
fi;  

cd $rus_dir;

echo "========================================";
echo "translation: ${rus_dir}/${file}.rus --> ${smm_dir}/${file}.smm";
echo "========================================";
echo;

${bin_dir}/mdl \
	-t -w -v \
	--deep-write \
	--mem-all --info-all \
	-o ../${smm_dir}/${file}.smm \
	\
	${file}.rus;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

cd ..;

if ! [ -d $smm_dir ]
then
    mkdir $smm_dir;
fi;  

cd $smm_dir;

echo "========================================";
echo "verifying: ${smm_dir}/${file}.smm with smm" ;
echo "========================================";
echo;

${bin_dir}/smm \
	-v --show-stack \
	--mem-all --info-all \
	\
	${file}.smm;

if [ $? != 0 ] 
then 
    echo "TEST FAILED."; 
    exit
else 
    echo;
    echo;
    echo "Tests successfully passed :)"; 
fi;

