#!/bin/sh

# mm/mdl reproving test
# argument - the name of the source file to be reproved

if [ -z $1 ] 
then echo "NO INPUT FILE."; exit
fi;

file=$1

math_dir='../math'; 
bin_dir='../../../bin';

echo "=======================================";
echo "translation: ${file}.mm --> ${file}.rus";
echo "=======================================";
echo;
${bin_dir}/mm \
	-w -t -v \
	--correct-grammar ${math_dir}/grammar.corr \
	--correct-symbol ${math_dir}/symbol.corr \
	--mem-all --info-all \
	-o ${math_dir}/${file}.rus \
	\
	${math_dir}/${file}.mm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "=============================================";
echo "reducing: ${file}.rus --> ${file}_reduced.rus";
echo "=============================================";
echo;

${bin_dir}/mdl \
	-w -v \
	--mem-summary --info-all \
	--refactor \
	--remove-redundancy \
	--info-refactoring \
	-o ${math_dir}/${file}_reduced.rus \
	${math_dir}/${file}.rus;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "================================================";
echo "reproving: ${file}_reduced.rus --> ${file}_reproved.rus";
echo "================================================";
echo;

${bin_dir}/mdl \
	-w -v \
	--stack-volume 128m --time-limit 30m \
	--prove-in-heap \
	--threads 1 \
	--reprove \
	--grow-up-determined \
	--grow-up-limit 1 \
	--grow-down-determined \
	--grow-down-limit 3 \
	--mem-balance \
	--mem-summary \
	--info-all \
	-o ${math_dir}/${file}_reproved.rus \
	${math_dir}/${file}_reduced.rus;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "================================================";
echo "translating: ${file}_reproved.rus --> ${file}_reproved.smm";
echo "================================================";
echo;

${bin_dir}/mdl \
	-t -w -v \
	--mem-all --info-all \
	-o ${math_dir}/${file}_reproved.smm \
	${math_dir}/${file}_reproved.rus;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;


echo "====================================";
echo "verifying: ${file}_reproved.smm with metamath";
echo "====================================";
echo;

${bin_dir}/metamath \
	"read ${math_dir}/${file}_reproved.smm" \
	'verify proof *' \
	exit 

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "===============================";
echo "verifying: ${file}_reproved.smm with smm" ;
echo "===============================";
echo;

${bin_dir}/smm \
	-v --show-stack \
	--mem-all --info-all \
	\
	${math_dir}/${file}_reproved.smm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
else echo "\n\nTests successfully passed :)"; 
fi;

