#!/bin/sh

# mm/mdl translation test
# argument - the name of the source file to be translated

if [ -z $1 ] 
then echo "NO INPUT FILE."; exit
fi;

file=$1

# We are located at /usr/share/mdl/scripts

math_dir='../math'; 
bin_dir='../../../bin';

echo "=======================================";
echo "translation: ${file}.mm --> ${file}.rus";
echo "=======================================";
echo;
${bin_dir}/mm \
	-w -t -v \
	--correct-grammar ${math_dir}/grammar.corr \
	--correct-symbol ${math_dir}/symbol.corr \
	--mem-all --info-all \
	-o ${math_dir}/${file}.rus \
	\
	${math_dir}/${file}.mm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "========================================";
echo "translation: ${file}.rus --> ${file}.smm";
echo "========================================";
echo;

${bin_dir}/mdl \
	-t -w -v \
	--mem-all --info-all \
	-o ${math_dir}/${file}.smm \
	${math_dir}/${file}.rus;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "====================================";
echo "verifying: ${file}.smm with metamath";
echo "====================================";
echo;

${bin_dir}/metamath \
	"read ${math_dir}/${file}.smm" \
	'verify proof *' \
	exit 

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
fi;

echo "===============================";
echo "verifying: ${file}.smm with smm" ;
echo "===============================";
echo;

${bin_dir}/smm \
	-v --show-stack \
	--mem-all --info-all \
	\
	${math_dir}/${file}.smm;

if [ $? != 0 ] 
then echo "TEST FAILED."; exit
else echo "\n\nTests successfully passed :)"; 
fi;

